### ISSUE TITLE
Action Required: Fix Renovate Configuration

### ISSUE THREAD

**Issue by ScriptedAlchemy** [module-federation/rollup-federation#9]
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

File: `renovate.json`
Error type: The renovate configuration file contains some invalid settings
Message: `packageRules: Each packageRule must contain at least one selector (paths, languages, baseBranchList, managers, datasources, depTypeList, packageNames, packagePatterns, excludePackageNames, excludePackagePatterns, sourceUrlPrefixes, updateTypes). If you wish for configuration to apply to all packages, it is not necessary to place it inside a packageRule at all.`

**Comment by maraisr** [comment]
@ScriptedAlchemy reckon you can turn off whatever tooling you used to get renovate working? I've got the bot configured now.

**Comment by ScriptedAlchemy** [comment]
Ahhhhh yes I can. My bad
